production:
  cloud_name: "social-scout"
  api_key: "926337359393654"
  api_secret: "CWUVM_HMTE6qHpV8aSKeIU1hi9U"

development:
  cloud_name: "social-scout"
  api_key: "926337359393654"
  api_secret: "CWUVM_HMTE6qHpV8aSKeIU1hi9U"

